### ISSUE TITLE
Whispers do not open the web widget

### ISSUE THREAD

**Issue by JaimeObregon** [smooch/smooch-js#100]
When whispers are sent to the user, the web widget remains closed by default, thus hidding the message to the user.

**Comment by lemieux** [comment]
Hey @JaimeObregon, by design the whispers are considered normal messages as part of your conversation with your user. We unfortunetaly do not have a way to tell client side what is a whisper or not, but we are definitely in considering it for a future release. Clearly, it has a use.

In the meantime, I'm checking if I could hack a script that you could add to your website to do exactly that without having to fork the widget. We could infer that if the first message in a conversation is from you and not from the user, it's a whisper and should open the widget. Would it work for you?

**Comment by lemieux** [comment]
Alright I just tested that snippet and it should do the trick for an on boot whisper 

```
SupportKit.init(...).then(function(){
            var conversation = SupportKit._chatController.conversation;
            if(conversation.get('messages').length === 0) {
                conversation.get('messages').once('add', function(message){
                    var isAppMaker = !!conversation.get('appMakers').get(message.get('authorId'));

                    if(isAppMaker) {
                        SupportKit.open();
                    }
                });
            }
        });
```

This will listen for the first message of a conversation to come up and checks if it's from the app maker (you) or not. If the conversation is already started with message, nothing is bound.

I just talked with the team and I confirm we will add the whisper flag on message in a future release. We'll make sure to trigger an event too which makes me thinks we could trigger an event too for receiving a message.

**Comment by JaimeObregon** [comment]
I confirm this workaround works as explained. Thank you, @lemieux!

**Comment by AndresPF** [comment]
I tried implementing this with no success so I did it another way. 

Sharing it in case someone needs it:
```
Smooch.init(...).then(function () {
    Smooch.getConversation().then(function(conversation) {
        if (conversation.messages.length > 0 && conversation.unreadCount > 0) {
            var checkLast = conversation.messages[conversation.messages.length - 1];
            if (checkLast.role == "whisper") {
                Smooch.open();
            }
        }
    });
});

**Comment by lemieux** [comment]
Hey @AndresPF,

you could also do

```
Smooch.on('message:received', function(message) {
    if (message.role == "whisper") {
           Smooch.open();
     }
});
```

after having `init` it properly.

**Comment by AndresPF** [comment]
Thanks @lemieux!

That is much simpler haha
