### ISSUE TITLE
Overriding user properties

### ISSUE THREAD

**Issue by DavidReinberger** [smooch/smooch-js#206]
Is there a way to override user properties? Right now, if you specify a property, another call to `userUpdate()` with the same property eg. `properties.brand`, does not update the brand property.

Updating the user profile when he logs in, is also doing nothing, only the email is visible, `givneName`, `surname` and `userId` are not shown when calling `/sk !profile` in slack.

Also updating properties does not fire "updated" notification in slack.

**Comment by lemieux** [comment]
Hey @DavidReinberger, I just checked this out and I think I'll need a code example because I can't repro your problem. I tried calling `updateUser` with the same prop key and different value and they get updated correctly. They also show up in Slack when doing `/sk !profile`. 

> Also updating properties does not fire "updated" notification in slack.

Only the email address will trigger that notification, but I don't think we documented that anywere, sorry about that :(. The rationale behind this is that updating properties could generate a lot of spam in Slack for a lot of people if we were sending that notification everytime the property changed. 

I'll close this until a code snippet is provided since I can't do much currently.

**Comment by DavidReinberger** [comment]
I've used code from the documentation, which did not work.
```
Smooch.updateUser({
    properties: {
      key: value
    }
});
```
So I've made myself a tiny wrapper around your rest api, to update the user, which works flawlessly.

Could you make an option to trigger the notification? Sometimes it could come in handy. For instance we are using the props to track user flow thru our order (category, subcategory, item/s selected, checkout step). If the user encounters a problem/wants to ask a question, the "operator" could use a feed back from the app, what the user is doing in real time, preferably controllable via Slack (smthing like `/sk !sub` and `/sk !stopsub`, with the option to make `/sk !sub` the default).
