### ISSUE TITLE
Any plans for option to config widget as appMaker with specific conversation id/user id?

### ISSUE THREAD

**Issue by tez123z** [smooch/smooch-js#232]
From the docs i didn't see any options that could configure the widget with role : 'appMaker' with a specific user or/conversation. Am I missing something? Are there any future plans to do this? could be cool.

**Comment by lemieux** [comment]
Hey @tez123z,

this is unfortunately not something we are looking to support in the foreseeable future. You can always fork the widget and make it work with our API! 

I'll close this issue since there's nothing to be done in this repo, but can you tell me more about the use case where you need to use the widget as an app maker?

**Comment by tez123z** [comment]
Hey - thanks for the response - yes in particular I was hoping to have the
capability to configure the widget in an 'appMaker' role and specify the
userId so as to use the widget for a particular conversation. We use smooch
for our app and have integrated with Slack but would prefer to add the
widget to our custom backend so we can view the info tied to each specific
customer (orders etc..) and the chat all in one place.

I'll fork it asap - any helpful hints as to where i should start with the
customization?

**Comment by lemieux** [comment]
Ehhhh , good question :) Now that I think more about it, it would be a hard task. You'll probably have to strip most of it and only keep the UI + message management part. All the rest would need to be redone because it's all appUser oriented.

Unless you really don't want to build your own UI, I suggest you do a server-to-server integration instead with our API and webhooks and go from there. Our websocket endpoint only works for appUsers, it would be hard to get realtime chat with our widget.

Also, you can checkout https://frontapp.com/ they have a pretty awesome dashboard that works very well with Smooch.

**Comment by tez123z** [comment]
I was afraid of that - :/

No worries - I've been looking for a good excuse to use React.js and rails Action Cable :) - i'll take a look at frontapp too - thanks for the tip!

**Comment by crayment** [comment]
Just want to voice another vote for this feature. We were hoping to embed an `appMaker` chat into our website as easily as it was for the `appUser` role and then just simply add some custom controls in a sidebar that help compose messages with the correct deeplink buttons. Being forced to use an integration to another service on the `appMaker` side seems pretty limiting.

**Comment by lemieux** [comment]
@crayment I'll make sure pass this to the product team!
