### ISSUE TITLE
Chat heads

### ISSUE THREAD

**Issue by schickling** [smooch/smooch-js#244]
Are there any presets for chat head "bubbles" similar to Intercom? So replacing the "How can we help?" element by a round picture?

**Comment by lemieux** [comment]
Hey @schickling, unfortunately it's not something with offer as a built-in feature of the widget. However it's something we considered doing and I'll forward your interest to the product team.

In the meantime, you can always fork and make your own custom header for the widget!

I'll close this issue since there's nothing really to be done at this point in the repo.
