### ISSUE TITLE
Sluggish scrolling using smooch with video background website

### ISSUE THREAD

**Issue by kenhuang** [smooch/smooch-js#372]
Hi, for some reason, scrolling feeling really sluggish when using smooch with video background website.

We use vide for our website:
http://vodkabears.github.io/vide/

Please help!

**Comment by kenhuang** [comment]
Actually after test it seems slow down by using this theme template:
https://html5up.net/overflow/download

**Comment by lemieux** [comment]
I'm not sure to understand the problem. From my quick test, the template seems a big sluggish with or without Smooch in it. 

I'll close this since I think it's more related to the template than it is to the Smooch widget. Feel free to reopen this if you have more information that points toward the widget being the problem.
