### ISSUE TITLE
Manually reset unreadCount

### ISSUE THREAD

**Issue by dunice** [smooch/smooch-js#377]
Is there a way to manually reset unreadCount property from a conversation using the JS SDK?

**Comment by lemieux** [comment]
Unfortunately, the widget doesn't expose that functionnality. However, [smooch-core](https://www.npmjs.com/package/smooch-core) does. If you are using npm as your package manager, you can install it and it won't result in a duplicate package since the widget uses it. 

I'll see if there's a clean way we could expose the core through the widget.

**Comment by lemieux** [comment]
Hey @dunice, just to let you know that smooch-js@3.5.1 was just released with the ability to access the internal smooch-core instance to let you make API calls by yourself.

In your case you would have to do the following : 

```js
Smooch.getCore().conversations.resetUnreadCount(Smooch.getUserId()).then(function() {
 // ...
});
```

Hope this help!
