### ISSUE TITLE
close chat window in mobile view when using back button on smartphone (Android)

### ISSUE THREAD

**Issue by skolarianer** [smooch/smooch-js#388]
On smartphones the chat window is displayed in fullscreen mode, which is great. But when pressing the back button on Android I would expect that the chat window closes instead of browsing back completey to previous page.

Outcome:
Website visitor opens page. Visitor clicks on chat bubble but doesn't use chat. Visitor presses back button. Visitor leaves website unintentionally and is lost.

**Comment by lemieux** [comment]
Hey @skolarianer,

unfortunately that's not something we plan to implement. The reason is that in order to achieve that, we would need to make the browser change it's URL using the History API. The problem with it is that the widget is used in a lot of different use cases, single page apps being one of them.

From experience, a single page app will most likely want to take control of the History API for multiple reasons and if something external is starting to interact with the history, it could lead to unexpected problems.

You maybe could find a solution to implement on your side using `Smooch.on('widget:opened', function() {..})`, `Smooch.on('widget:closed', function() {..})`, and `Smooch.close()` in combination with the History API.
