### ISSUE TITLE
Smooch logout on Isomorphic React Apps

### ISSUE THREAD

**Issue by adrianha** [smooch/smooch-js#402]
Hi,
I was invoking logout function on my apps,
but chat history wasnt be removed and when i logged i using another account,
it will updated last user data when i checked it on slack.
Any idea?
Thank you

**Comment by lemieux** [comment]
Hey @adrianha,

are you identifying your users using a user id when starting the web messenger? (http://docs.smooch.io/javascript/#users-on-multiple-devices)

 If not, logging out an anonymous user won't do much since the next anonymous user will be merged with the previous one and the conversation history will follow.

Let me know if that was it.

**Comment by adrianha** [comment]
Hi @lemieux,
The problem is i was identifying user's user id using auto increment given by API.. Somehow it broke the identifying process on smooch. But when i used email as user id, it works well.
So theres no issue when using email as user id..

Thank you!
Smooch is really great 👍

**Comment by dannytranlx** [comment]
@adrianha Great news! 

> So theres no issue when using email as user id..

However, we usually don't recommend you to use emails as identifier since they are easily guessable. You may keep the emails as userId if you add JWT as part of your identification. See more on http://docs.smooch.io/javascript/#authenticating-users-optional
