### ISSUE TITLE
Error message for failed Init

### ISSUE THREAD

**Issue by thielCole** [smooch/smooch-js#421]
Could you guys provide some error message when initializing Smooch. example code

```
Smooch.init({'appToken':<token>}).catch((error) => {
  console.log('Smooch init error:', error);
}
```

I don't see any mention of this in the documentation, and in the code all I don't see Promise.reject from init(props), just Promise.resolve.

**Comment by lemieux** [comment]
Hey @thielCole, if you don't see `Promise.reject` it's mainly because the only reason why `Smooch.init` would cause an "expected" error would be from bad parameters sent to the server and all http requests are handled by smooch-core. 

Since the documentation says that `init` will return a promise, I'm not sure what else could be done.


Did you encounter a problem where an error was thrown without a message?

**Comment by thielCole** [comment]
@lemieux I did encounter a problem while integrating with my ionic2 application, but a standard promise catch did not return anything. That is why I asked, there were no error codes like 400 for bad parameters, or a error object returned so I was shooting in the dark trying to solve the problem.

It turns out that the issue was that you cannot run smooch with a hybrid web application that uses UIWebView, so instead I had to upgrade using the Wkwebview plugin. But I figured this out literally through guess and check, not through any error messages that I could find.

**Comment by lemieux** [comment]
I'm not sure how the lib could detect that and return a proper error. Unless you are sure the error came from within the lib, I can't do much here. The whole `init` call is a promise chain. If something fails in it, you should be able to catch it.

**Comment by lemieux** [comment]
I'll close this since it seems related to handling errors out of our control.
