### ISSUE TITLE
Error __jsonpXX__ is not defined

### ISSUE THREAD

**Issue by thielCole** [smooch/smooch-js#441]
After implementing smooch in my Ionic 2 application, I am receiving some weird errors on an Android device. I am seeing these types of errors while the application is running in the background. I will try and reliably reproduce this.

```
ReferenceError: __jsonp30__ is not defined
1
File https://api.smooch.io/faye line 1 col 5 in [anonymous]
```

I am wondering if you have seen this error before, or if my library is just blaming smooch because it is reporting through smooch's error handling implementation.

**Comment by jpjoyal** [comment]
We currently don't support or test specifically for Ionic. For any mobile app, we recommend using our high quality native [iOS](https://github.com/smooch/smooch-ios) and [Android](https://github.com/smooch/smooch-android) SDKs for the best user and developer experience. Ionic support via our Web messenger is not currently one of our priority but we always welcome PRs for Web messenger since its fully open source.

**Comment by thielCole** [comment]
Just for reference, I ended up figuring this out. What happens is that when the device suddenly looses connection but is running in the background, the smooch web socket throws an error that is not caught. It might show up in your web messenger as well? Just thought I should update this.
