### ISSUE TITLE
Wheel event listener causing performance hit while scrolling

### ISSUE THREAD

**Issue by danielcardoso5** [smooch/smooch-js#474]
A wheel event listener is added to the document element after smooch loads. This causes a performance hit while scrolling the pages where smooch.js is included.

What's the reason for this event to be added? The scroll event listener is also present and doesn't affect scrolling performance that much.

The issue can be seen in Chrome dev tools, in the rendering tab by enabling the scrolling performance issues checkbox.

**Comment by lemieux** [comment]
Seems like React does that by itself based on https://github.com/facebook/react/issues/1254. From what I understand from this issue is that whenever you use `onWheel` in your React tree, it will bind it to the document too which is not really desired.

I checked where we use `onWheel` and I'll bring it up to the team to see how we could work around this problem.

Thanks for the report!

**Comment by danielcardoso5** [comment]
Hi @lemieux, any update on this issue?

**Comment by alavers** [comment]
I suspect https://github.com/smooch/smooch-js/pull/503 fixes this issue :)

**Comment by danielcardoso5** [comment]
I can confirm that it's fixed. Thanks @alavers @lemieux :)
