### ISSUE TITLE
Issue with the smooch chat dialog causing the html to break on Firefox.

### ISSUE THREAD

**Issue by alin-rosu** [smooch/smooch-js#481]
This is how the page looks like in Chrome, when smooch is closed: https://s3.amazonaws.com/uploads.hipchat.com/39260/829560/ByURnsF2qd3laSO/upload.png As you can see. the bottom of the page is fixed, so I cannot move past that. But on Firefox, when the smooch chat dialog is closed, the page looks like this: https://s3.amazonaws.com/uploads.hipchat.com/39260/829560/BCrKoabYoWYjH0j/upload.png The chat windows being closed, should not be visible, but if I scroll down, it is there. If I open the chat, then the extra spacing disappears, and I cannot scroll the page down (it fixes the issue): https://s3.amazonaws.com/uploads.hipchat.com/39260/829560/5NraM0G864Qf1mU/upload.png But this is only until I close it again, which will make it add the extra spacing, making the page scrollable. This is how I initiate smooch:
http://pastebin.com/FZ4WZYPH
Is this fixable? PS: it works on Chrome and Safari, so far only Firefox has this issue.

**Comment by lemieux** [comment]
Hey @alin-rosu, after checking out the link you provided us via chat, it seems like there's a `-webkit-transform: translateZ(0)` rule on `html, body'  that makes `position: fixed` go crazy. Seems like a known behavior according to http://stackoverflow.com/questions/28157125/why-does-transform-break-position-fixed.

I'll close this since it's not something we can fix on our side.

**Comment by alin-rosu** [comment]
Thanks, that actually fixed it.
