### ISSUE TITLE
Filtering received messages

### ISSUE THREAD

**Issue by mrazzari** [smooch/smooch-js#506]
I'm trying to modify messages as they're received. Say, append a "**!**" to all messages.

I set up a listener, and modified the message. 
But it only gets updated after a second or so refresh interval. 

As a workaround, I found that `getConversation` triggers the update as expected:

```javascript
Smooch.on("message:received", function(message){
	message.text += "!";
	Smooch.getConversation();		
});
```

But this does seem a bit of a hack. Is there any "proper" way to do it?

**Comment by lemieux** [comment]
Hey @mrazzari, that's indeed a bit of a hack since we don't expect messages to be modified, but unfortunately modifying messages when they come in is not something that is supported on the Web Messenger. Your workaround should be working, but we can't guarantee that we won't make a change in the future that might break it.

**Comment by mrazzari** [comment]
Would be great to have this supported at some point. There are several use cases for this. 

* Tweak message.text to point an URL to a different environment (dev vs staging vs prod)
* Improve message.avatarUrl on customer channels that don't support it (helloumi, motion)
* Add message.actions that are specific to the Web context
* Convert smileys to gifs, support markdown, etc
* etc

**Comment by lemieux** [comment]
Yeah we talked about it internally and it would be an interesting feature to have. I'll bring this up to the product team to see what they think about it.
